### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by wqw547243068** [adilmoujahid/blockchain-python-tutorial#1]
Hello, it doesn't work when executing the follow command in Windows 10+python3.6:
```shell
python blockchain.py -p 5000
```
The error information is:

> ModuleNotFoundError: No module named 'Crypto'

Then, after installed crypto
> pip install crypto

Another problem appears:
> ModuleNotFoundError: No module named 'Crypto.Random'

Any pip package needed to install before ? If so, would you please append the requirement file ?
Thanks for your sharing!

**Comment by curtisstpierre** [comment]
I took a crack at fixing the dependency issue locally looks like I needed to do
```
pip install pycrypto
pip install requests
pip install Flask
```
this is my requirements file
```
certifi==2018.1.18
chardet==3.0.4
click==6.7
Flask==0.12.2
idna==2.6
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
pycrypto==2.6.1
requests==2.18.4
urllib3==1.22
Werkzeug==0.14.1
```

**Comment by mahmoodtava** [comment]
i installed anaconda and every package it need are there 
it works good

**Comment by harshitsinghal12** [comment]
plz help me facing the same issue. how to run this on anaconda?

**Comment by ChiCongNguyen** [comment]
pip install Crypto

It works for me
