### ISSUE TITLE
Blockchain Nodes are not sync

### ISSUE THREAD

**Issue by mahmoodtava** [adilmoujahid/blockchain-python-tutorial#2]
hi all
i run  blockchain.py on 3 or 4 different port 
in configure tab in every blockchain node i added another node addreses
but when i mine a block in for example node 1 when i press refresh button in every blockchain node Nothing happen and nodes are not sync

in addition i use win10 and i run it under Spyder 
in spyder i have 4 console that every blockchain.py run at that console 
and every thing work except node synnc

**Comment by adilmoujahid** [comment]
You have to add manually the IP addresses of the nodes in the config page before clicking on sync button.

**Comment by mahmoodtava** [comment]
hi adil 
 thank u for your good post and answer
i have 3 blockchain node 
there URLs are : 
127.0.0.1:5000
127.0.0.1:5001
127.0.0.1:5002

I add manually these URLs in the config page on each blockchain node 

I made some transaction and send them to blockchain nodes 
for example 2 transactions to node 127.0.0.1:5000
3 transactions to node 127.0.0.1.5001 
and so on ...
 
then i mined them and the transactions added to blockchain correctly
when i click on refresh button to sync the blockchain in every nodes the blockchain does not sync and refresh
 :(
i took some screenshots that may be help.
![screenshot 11](https://user-images.githubusercontent.com/33554292/37735039-2849e8ae-2d62-11e8-96be-c7c3776e936a.png)
![screenshot 12](https://user-images.githubusercontent.com/33554292/37735043-28763fa8-2d62-11e8-9f96-f3b74e396a23.png)
![screenshot 13](https://user-images.githubusercontent.com/33554292/37735044-28edab42-2d62-11e8-9cd5-c357ef1e10c9.png)
![screenshot 14](https://user-images.githubusercontent.com/33554292/37735045-291e256a-2d62-11e8-83af-052b412ab93b.png)
![screenshot 15](https://user-images.githubusercontent.com/33554292/37735046-294e7918-2d62-11e8-8016-fa42ac44bb0c.png)
![screenshot 16](https://user-images.githubusercontent.com/33554292/37735047-29850b72-2d62-11e8-9aa7-9b92a9ce9c89.png)
![screenshot 17](https://user-images.githubusercontent.com/33554292/37735048-29b43ba4-2d62-11e8-8139-497c141ba5a3.png)
![screenshot 18](https://user-images.githubusercontent.com/33554292/37735050-29e699b4-2d62-11e8-9452-ec910d9455e6.png)
![screenshot 19](https://user-images.githubusercontent.com/33554292/37735051-2a138cf8-2d62-11e8-8cc9-1115963787dd.png)




tanx again for your good works

**Comment by adilmoujahid** [comment]
Hi mahmood,

I fixed the issue. The sync function should work fine with the updated code.

**Comment by mahmoodtava** [comment]
u r good man 
thank u
